# -*- coding: utf-8 -*-
"""Capsule_COVID Data Visualization_AllisonXU

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWlOBL-jY-rPJj3-Ddekq0Bcjbh_QLhc

<h1 align="center">
    NSDC Data Science Projects
</h1>
  
<h2 align="center">
    Project: DATA VISUALIZATION PROJECT - COVID-19 ANALYSIS
</h2>

<h3 align="center">
    Name: Allison Xu
</h3>

### **Project Description**
The NSDC DSPs provide virtual collaboration and networking opportunities for data science learners of all ages and skill levels, aiming to develop new data pre-processing, visualization, storytelling, and programming skills. Studying COVID-19 data is crucial as it helps us understand the virus's spread, the effectiveness of interventions, and its overall impact on populations. Data visualization plays a key role in transforming raw data into meaningful insights, making complex information more accessible and understandable.

In this project, we will explore various datasets related to COVID-19, including vaccination rates, infection rates, and death counts. We will employ descriptive statistics to summarize the data, use data visualization techniques to uncover trends and patterns, and interpret these visualizations to derive actionable insights. By the end of this project, students will have a better understanding of how to handle large datasets, apply statistical methods, and create compelling visual narratives.

Our goal is to equip you with the skills needed to analyze and interpret real-world data, developing a deeper appreciation for the power of data science in addressing global challenges.


### **Goals**
- **Data Analysis**: Analyze vaccination rates, infection rates, and death counts.
- **Visualization**: Create visualizations to uncover trends and patterns.
- **Interpretation**: Derive actionable insights from the data.

### **Tools and Libraries**
- **Python**: Programming language
- **Pandas**: Data manipulation
- **Matplotlib/Seaborn**: Data visualization
- **Plotly**: Interactive plots
- **IPython Widgets**: Interactive elements

**Note:** You are free to use other libraries apart from the ones we have recommended

### **Please read before you begin your project**

**Instructions: Google Colab Notebooks:**

Google Colab is a free cloud service. It is a hosted Jupyter notebook service that requires no setup to use, while providing free access to computing resources. We will be using Google Colab for this project.

In order to work within the Google Colab Notebook, **please start by clicking on "File" and then "Save a copy in Drive."** This will save a copy of the notebook in your personal Google Drive.

Please rename the file to "Capsule - COVID Data Visualization - Your Full Name." Once this project is completed, you will be prompted to share your file with the National Student Data Corps (NSDC) Project Leaders.

You can now start working on the project. :)

**Additional resources**

We would utilise the seaborn library to create visualizations in this notebook. To learn more about the Seaborn library visit: https://seaborn.pydata.org/

Please feel free to refer to the Northeast Big Data Innovation Hub [Flashcard series](https://www.youtube.com/playlist?list=PLNs9ZO9jGtUDxKBBZa5ImsV9h9hlLwJWH) to learn about various visualization techniques and understand the ways to analyze the data effectively.

# Milestone #1: Data Preparation & Exploration

**Dataset Details:**
The dataset used in this project includes various aspects of COVID-19 data such as vaccination rates, infection rates, and death counts. The data is sourced from reliable institutions such as the World Health Organization (WHO), Johns Hopkins University, and other governmental health agencies. These datasets provide a comprehensive view of the pandemic's impact across different regions and time periods.

**Step 1:**

Setting up libraries and installing packages

To install a library:
```python
 import <library> as <shortname>
```
We use a *short name* since it is easier to refer to the package to access functions and also to refer to subpackages within the library.
"""

import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

"""These are the libraries that will help us throughout this project. We encourage you to read more about the important and most commonly used packages like Pandas, Numpy, MatplotLib and Seaborn, and write a few lines in your own words about what they do. [You may use the Data Science Resource Repository (DSRR) to find resources to get started!](https://nebigdatahub.org/nsdc/data-science-resource-repository/)

**TO DO:** Write 3-5 sentences about commonly used packages and what they're used for.

>*

**Step 2:**

Let’s access our data. We will be using the COVID dataset. The dataset contains COVID data from around 187 countries.
Link to the dataset: [Covid-19 dataset](https://www.kaggle.com/datasets/imdevskp/corona-virus-report)


We will use Pandas to read the data from the csv file using the `read_csv` function. This function returns a Pandas dataframe. We will store this dataframe in a variable called `data`.

**Note:** Fill in the blanks to complete the code below.
"""

# TODO: Read the data using pandas read_csv function
data = pd.read_csv('country_wise_latest.csv')

"""To look at some data values, we can use the `head` function to look at the first five values"""

# from google.colab import drive
# drive.mount('/content/drive')

# TODO: Print the first 5 rows of the data using the head function of Pandas
data.head()

"""Now, let's take an initial look at the data including some descriptive statistics. Learn more about descriptive statistics with [this NSDC Flashcard video series.](https://www.youtube.com/playlist?list=PLNs9ZO9jGtUDxKBBZa5ImsV9h9hlLwJWH)

We will use the `describe` function to review the data.
"""

# TODO: Describe the data using describe function of pandas
data.describe()

"""**Step 3:** </br>
Let's take a look at how different variables of our data are correlated with each other.
We can use the `corr` function for this.
To plot these relationships, we can use a `pairplot`. You can read more about this method [here](https://seaborn.pydata.org/generated/seaborn.pairplot.html).

"""

# TODO: Plot a correlation/pairplot using Seaborn library in Python
print(data[['Deaths','Recovered']].corr())
sns.pairplot(data[['Deaths','Recovered']])
plt.show

"""# Milestone #2: Geographic Analysis

**Step 1:** Let us do some analysis on the [WHO Regions of the Americas](https://www.paho.org/en/countries-and-centers). To do so, we will need to create a subset of our master dataset.
To create a subset of the main dataset, we will be using the slicing method.

**Why focus on the Americas?**

The Americas were chosen for this analysis due to their diverse responses to the COVID-19 pandemic, varying healthcare infrastructure, and different socio-economic impacts. This regional focus allows us to compare and contrast the effectiveness of different strategies and the overall impact of the pandemic in countries with different characteristics.

Let's understand why the Americas are important by visualizing various features from the dataset.
"""

# TODO: Aggregate data by WHO Region
who_region_data = data.groupby('WHO Region').sum().reset_index()
who_region_data

# TODO: Plot the trends for confirmed cases, deaths, and recoveries across WHO regions
fig, axes = plt.subplots(3, 1, figsize=(12, 18))

sns.barplot(ax=axes[0], x='WHO Region', y='Confirmed', data=who_region_data)
axes[0].set_title('Confirmed Cases by WHO Region')
axes[0].set_ylabel('Confirmed Count Across WHO Regions')

sns.barplot(ax=axes[1], x='WHO Region', y='Deaths', data=who_region_data)
axes[1].set_title('Deaths by WHO Region')
axes[1].set_ylabel('Death Count Across WHO Regions')

sns.barplot(ax=axes[2], x='WHO Region', y='Recovered', data=who_region_data)
axes[2].set_title('Recoveries by WHO Region')
axes[2].set_ylabel('Recovered Count Across WHO Regions')

plt.tight_layout()
plt.show()

#TODO: Filter the data for the Americas region
d_america = data[data['WHO Region'] == 'Americas'].sort_values(by='Confirmed', ascending = False)
new_data = d_america.head(10) #top 10 countries
new_data

"""**Step 2**: Calculate descriptive statistics of our new data set (for only Americas i.e. North and South America)"""

#TODO: Calculate the descriptive statistics for new_data. Review how we did this above if you need a refresher!
new_data.describe()

"""# Milestone #3: Data Visualizations

**Step 1:** Let us create some plots and graphs to further visualize our data. We will start with a barplot for which we will use the Seaborn library.

Need a refresher on bar charts? [Review this video for a quick reminder](https://www.youtube.com/watch?v=Y_HCxHOy4Sw&list=PLNs9ZO9jGtUDxKBBZa5ImsV9h9hlLwJWH&index=28&pp=iAQB)!
"""

active = new_data[['Country/Region','Active']].sort_values(by='Active',ascending=False)
sns.barplot(y=active.get('Country/Region'),x=active.get('Active'))

"""**TO DO:** Review the above chart and write 2-5 sentences about your interpretation.
 </br>Note: When interpreting graphs, look for key trends and patterns. Use specific numbers to back up your observations. For example, if you notice a peak in infection rates, mention the exact date and value. Compare different regions or time periods to highlight significant differences or similarities. Your interpretation should provide a clear narrative that explains what the data shows and why it is important.

>*  For countries in the Americas, the US had far more active counts than any other countries, with almost five times more active counts than Brazil, the country with the second most active counts. This strongly suggests that the US suffered the most from COVID-19 within the Americas.

**Step 2:** Now, we will plot a double bar chart to compare Confirmed and Recovered COVID Cases in different countries. You can learn more about grouped bar charts here:
https://www.geeksforgeeks.org/plotting-multiple-bar-charts-using-matplotlib-in-python/.
"""

#TODO: plot a double bar chart
plt.figure(figsize=(10, 5))
X_axis = np.arange(len(new_data['Confirmed']))
plt.bar(X_axis - 0.2,new_data['Confirmed'] , 0.4, label = 'Confirmed')
plt.bar(X_axis + 0.2, new_data['Recovered'], 0.4, label = 'Recovered')

plt.xticks(X_axis,new_data['Country/Region'] )
plt.xlabel("Confirmed")
plt.ylabel("Recovered")
plt.title("Comparing the Confirmed and Recovered Counts in the Americas")

plt.legend()
plt.show()

"""**TO DO:** Review the above chart and write 2-5 sentences about your interpretation.

>*  For countries in the Americas, the US and Brazil has the most confirmed and recovered patients.
>*  While the US had more confirmed counts, Brazil had more Recovered patients, suggesting Brazil had better control over the pandemic than the US.
>*  Smaller countries like Mexico and Chile had about the same amount of confirmed and recovered patients, which means these countries had effective control over the pandemic.

**Step 3:** Now, let's plot a pie chart. [Click here to review when a pie chart should be used!](https://www.youtube.com/watch?v=AqqA3cP1zGo&list=PLNs9ZO9jGtUDxKBBZa5ImsV9h9hlLwJWH&index=30&pp=iAQB)
<br> For plotting a pie chart we will be using the matplotlib package. To learn more, visit: https://matplotlib.org/
"""

#TODO: Plot a pie chart for the top 10 countries to show the Distributition of Recovered COVID Cases
plt.figure(figsize=(8,8))
patches, text, autotexts = plt.pie(new_data['Recovered'], labels = new_data['Country/Region'],autopct="%0.2f%%", pctdistance=0.8)
plt.title("Distribution of Recovered COVID Cases") #Hint: Check the TODO statement!
plt.axis('equal')
plt.legend(patches,new_data['Country/Region'] )
plt.show()

"""**TO DO:** Review the above chart and write 2-5 sentences about your interpretation.

>*  Brazil had the most amount of recovered COVID cases, suggesting its effective control over the pandemic.
>*  Canada had no recovered COVID cases, suggesting the need for improvements in its control strategies.

**Step 4:** Let us compare Active cases in the Americas using a Donut Chart.
You can also learn more about donut charts in Python here: https://matplotlib.org/stable/gallery/pie_and_polar_charts/pie_and_donut_labels.html

Feel free to experiment with parameters like colors, explosions, etc. to make it more readable.
"""

# TODO: Plot a donut chart for the top 10 countries
x = new_data['Active'].to_list()
labels = new_data['Country/Region']
# colors - feel free to experiment!
colors = ['#0F52BA','#4169E1', '#0096FF',
          '#87CEEB','#89CFF0', '#7DF9FF']
# explosion
explode = (0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05)

# Pie Chart
plt.pie(x, colors=colors, labels=labels,
        autopct='%1.1f%%', pctdistance=0.85,
        explode=explode)

# draw circle
centre_circle = plt.Circle((0, 0), 0.65, fc='white')
fig = plt.gcf()

# Adding Circle in Pie chart
fig.gca().add_artist(centre_circle)

# Adding Title of chart
plt.title('Active Cases in the Americas')

# Displaying Chart
plt.show()

"""**TO DO:** Review the above chart and write 2-5 sentences about your interpretation.

>* The US had the highest number of active cases in the Americas, accounting for over 70% of all active cases in the region. This indicates that the COVID situation in the US was the most severe in the Americas.

**Step 5:** Our next visualization will be a Heatmap ([What is a heatmap?](https://www.youtube.com/watch?v=MuHsSH590WY&list=PLNs9ZO9jGtUDxKBBZa5ImsV9h9hlLwJWH&index=33&pp=iAQB)). One of the ways to create these are Choropleth. We will be plotting a geospatial heatmap which is used to represent the density of distribution of data points on a map. <br>
<br> Choropleth maps can be plotted using plotly package in Python. To learn more about it visit: https://plotly.com/python/choropleth-maps/
"""

# TODO: Plot a Heatmap below for total confirmed cases in the Americas
fig = px.choropleth(new_data,
                    locations= 'Country/Region',
                    locationmode='country names',
                    color='Confirmed',
                    color_continuous_scale='Reds',
                    hover_name='Country/Region',
                    title='Total Confirmed Cases in the Americas')

# fig.update_geos(projection_type="natural earth")

fig.show()

"""**TO DO:** Review the above chart and write 2-5 sentences about your interpretation.

>*  North America generally had more confirmed COVID cases than South Anmerica.
>*  Although the US had the most serious pandemic, Canada wasn't affected really seriously.

**Step 6:** Calculate mortality and recovery rates, aggregate your data by WHO region, and then plot these rates using a barplot.

**Hint**: [Read this article to understand the formula we will be using](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9291733/) (we will use the one suggested by Battegay and their team).
"""

data

# Calculate mortality and recovery rates
data['Mortality Rate'] = (data['Deaths'] / data['Confirmed']) * 100
data['Recovery Rate'] = (data['Recovered'] / data['Confirmed']) * 100

# Aggregate data by WHO Region
# Ensure that non-numeric columns are not included in the mean calculation
numeric_columns = ['Confirmed', 'Deaths', 'Recovered', 'Active', 'Mortality Rate', 'Recovery Rate']

# Aggregate data by WHO Region
who_region_rates = data.groupby('WHO Region')[numeric_columns].mean().reset_index()


# Plot the mortality and recovery rates by WHO region
fig, axes = plt.subplots(2, 1, figsize=(8, 8))

sns.barplot(ax=axes[0], x='WHO Region', y='Mortality Rate', data=who_region_rates)
axes[0].set_title('Mortality Rate by WHO Region')
axes[0].set_ylabel('Mortality Rate (%)')

#Review the code directly above and use it to help you fill in the following code for "Recovery Rate"
sns.barplot(ax=axes[1], x='WHO Region', y='Mortality Rate', data=who_region_rates)
axes[1].set_title('Mortality Rate by WHO Regions')
axes[1].set_ylabel('Mortality Rate)')

plt.tight_layout()
plt.show()

"""**TO DO:** Review the above chart and write 2-5 sentences about your interpretation.

>*  Europe had the most mortality rate, suggesting the most serious pandemic conditions in Europe.
>*  South-East Asia and Western Pacific had the least mortality rate, suggesting their effective control during COVID-19.

# Milestone #4: Self-Guided Analysis of a Different WHO Region (other than America)

Choose any region within the dataset and create 3 different visualizations below. You may choose to use the same visualizations as above and compare your findings, or you may want to experiment with new visualizations.


**Be sure to give your interpratations for each visualization you create.**

Not sure which region to select? You may want to consider choosing a region that has a high mortality or recovery rate.
"""

asia_data = data[data.get('WHO Region') == 'South-East Asia']
asia_data

"""**TO DO:** Which region are you choosing and why? Write 2-3 sentences explaining your reasoning below.
>*  Southeast Asia was chosen as the focus region because it is geographically close to China, where COVID-19 was first reported. Due to this proximity, countries in Southeast Asia were exposed to the virus relatively early, making the region important for understanding how the outbreak spread and how different countries were affected.

**TO DO:** Begin creating your visualizations below.

The following scatter plot describes the relationship between the 1 week % increase and the recovery rate. The color of each point represents the amount of confirmed cases. The larger the point, the more confirmed cases.
"""

plt.scatter(asia_data.get('1 week % increase'), asia_data.get('Recovery Rate'), c = asia_data.get('Confirmed'), cmap = 'cividis')
plt.xlabel('1 Week % Increase')
plt.ylabel('Recovery Rate')
plt.title('Recovery Rate vs. 1 Week % Increase')

for i in range(len(asia_data)):
    x = asia_data.get('1 week % increase').iloc[i]
    y = asia_data.get('Recovery Rate').iloc[i]
    label = asia_data.get('Country/Region').iloc[i]

    plt.annotate(
        label,
        (x, y),
        textcoords="offset points",
        xytext=(5, 5),
        ha='center',
        fontsize=8
    )

plt.show()

"""**TO DO:** Review the above visualization and write 2-5 sentences about your interpretation.

>*  Overall, there is no strong linear relationship between the two variables. Countries with a low weekly increase can still have either high or low recovery rates. For example, Thailand, Bhutan, and Sri Lanka have low 1-week increases but relatively high recovery rates, suggesting that slower case growth may be associated with better recovery outcomes in some countries.
>*  On the other hand, India stands out as an outlier. It has the highest 1-week percentage increase, while its recovery rate is only moderate compared to other countries. This may indicate that rapid case growth can put pressure on healthcare systems, slowing recovery.
>*  Timor-Leste is another notable outlier, with both a very low increase and an extremely low recovery rate. This could reflect limited healthcare capacity or delays in reporting recoveries.

The second Data Visualization of data in Southeast Asia is a heatmap showcasing the mortality rate.
"""

fig = px.choropleth(
    asia_data,
    locations='Country/Region',
    locationmode='country names',
    color='Mortality Rate',
    hover_name='Country/Region',
    color_continuous_scale='Blues',
    title='COVID-19 Mortality Rate in Asia'
)

fig.show()

"""**TO DO:** Review the above visualization and write 2-5 sentences about your interpretation.

>*  From the heatmap, countries in Southeast Asia show noticeable variation in mortality rates. Some countries are shaded darker blue, indicating higher mortality rates, while others remain much lighter. This suggests that even within the same region, outcomes differed significantly.
>* Also, countries closer to China showed a lighter color, which means that geographic proximity alone does not fully determine mortality rate. Factors such as healthcare capacity, population density, government response, and reporting practices likely played a role in these differences.

The third visualization on the Southeast Asia region is a pie chart describing the amount of active cases in the top five countries.
"""

top5 = asia_data.sort_values('Active', ascending=False).head(5)
others = asia_data['Active'].sum() - top5['Active'].sum()

labels = list(top5['Country/Region']) + ['Others']
sizes = list(top5['Active']) + [others]

plt.figure(figsize=(10, 10))

wedges, texts, autotexts = plt.pie(
    sizes,
    labels=labels,
    autopct='%1.1f%%',
    startangle=140,
    colors = plt.cm.YlOrBr(np.linspace(0.4, 1, len(sizes))),
    wedgeprops={'edgecolor': 'white', 'linewidth': 1},
    pctdistance=0.5
)

for text in texts:
    text.set_fontsize(10)
for text in autotexts:
    text.set_fontsize(10)
    text.set_fontweight('bold')

plt.title('Distribution of Active COVID-19 Cases in Asia (Top 5 Countries)')
plt.axis('equal')

plt.show()

"""**TO DO:** Review the above visualization and write 2-5 sentences about your interpretation.

>*  A small number of countries account for a large proportion of active cases, while the remaining countries contribute a much smaller share.

**TO DO:** Did the different visualizations helped you to identify different insights? Share your thoughts below.
>*  While according to the pie chart, India had the most active cases, it's mortality rate wasn't the highest, suggesting its effective control over the pandemic.

**TO DO:** Did you notice any significant similarities or differences between the regions you analyzed throughout this project? Share your thoughts below.
>*  The CODIV cases are more concentrated, mostly in the southern part, while the cases in the Americas are more scattered.

---


### **Conclusion**



In this project, we explored various aspects of COVID-19 data through descriptive statistics and data visualization techniques. We analyzed datasets from different regions, with a specific focus on the Americas, to understand the pandemic's impact. By interpreting these visualizations, we derived meaningful insights that highlight the importance of data-driven decision-making in addressing global challenges like COVID-19. This project not only enhances your technical skills, but also underscores the crucial role of data science in tackling real-world issues.

---


## <font color='black'> **Thank you for completing the project!**</font>

In order to receive a certificate of completion, please share this notebook with er3101@columbia.edu. Do reach out to us if you have any questions or concerns. We are here to help you learn and grow.
"""